export const FORMATIONS_ECM = [
  'L1 Alternance',
  'L1 Initial',
  'L1 RPMS',
  'L1 International',
  'L2 Alternance LM',
  'L2 Alternance JV',
  'L3 CVM LMM',
  'L3 CVM MJV',
  'L3 RGAO LMM',
  'L3 RGAO MJV',
  'L3 RH LMM',
  'L3 RH MJV',
  'L3 Finance MJV',
  'L3 Finance LMM',
  'M1 CVM LMM',
  'M1 CVM MJV',
  'M1 RGAO LMM',
  'M1 RGAO MJV',
  'M1 RH LMM',
  'M1 RH MJV',
  'M1 Finance MJV',
  'M1 Finance LMM',
  'M2 CVM LMM',
  'M2 CVM MJV',
  'M2 RGAO LMM',
  'M2 RGAO MJV',
  'M2 RH LMM',
  'M2 RH MJV',
  'M2 Finance MJV',
  'M2 Finance LMM',
]
